[package]
name = "ndc-test"
description = "A tool to verify that a data connector is somewhat compatible with the specification"
version = "0.1.0"
edition = "2021"

[dependencies]
ndc-client = { path = "../ndc-client" }

async-trait = "^0.1.74"
clap = { version = "^4", features = ["derive"] }
colored = "^2.0.4"
indexmap = { version = "^2", features = ["serde"] }
reqwest = { version = "^0.11", features = ["json", "multipart"] }
semver = "^1.0.20"
serde = "^1.0.189"
serde_json = "^1.0.107"
thiserror = "^1.0.50"
tokio = { version = "^1.33.0", features = ["macros", "rt-multi-thread", "parking_lot"] }
rand = { version = "^0.8.5", features = ["small_rng"] }
