[package]
name = "ndc-test"
description = "A tool to verify that a data connector is somewhat compatible with the specification"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "^0.1.67"
clap = { version = "^4", features = ["derive"] }
indexmap = { version = "^1", features = ["serde"] }
ndc-client = { path = "../ndc-client" }
proptest = "^1.2.0"
reqwest = { version = "^0.11", features = ["json", "multipart"] }
semver = "^1.0.18"
serde_json = "^1.0.105"
thiserror = "^1.0.47"
tokio = { version = "^1.26.0", features = ["macros", "rt-multi-thread", "parking_lot"] }