[package]
name = "ndc-test"
description = "A tool to verify that a data connector is somewhat compatible with the specification"
version = "0.1.0"
edition = "2021"

[features]
default = ["native-tls"]
native-tls = ["ndc-client/native-tls", "reqwest/native-tls"]
rustls = ["ndc-client/rustls", "reqwest/rustls"]

[dependencies]
ndc-client = { path = "../ndc-client" }

async-trait = "^0.1.74"
clap = { version = "^4", features = ["derive"] }
colorful = "0.2.2"
indexmap = { version = "^2", features = ["serde"] }
rand = { version = "^0.8.5", features = ["small_rng"] }
reqwest = { version = "^0.11", features = ["json", "multipart"], default-features = false }
semver = "^1.0.20"
serde = "^1.0.189"
serde_json = "^1.0.107"
thiserror = "^1.0.50"
tokio = { version = "^1.33.0", features = ["macros", "rt-multi-thread", "parking_lot"] }
