[workspace]
resolver = "2"

package.version = "0.1.1"

members = [
  "ndc-client",
  "ndc-reference",
  "ndc-test",
]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# disable certain pedantic warnings
doc_markdown = { level = "allow" }
missing_errors_doc = { level = "allow" }
missing_panics_doc = { level = "allow" }
module_name_repetitions = { level = "allow" }
must_use_candidate = { level = "allow" }
return_self_not_must_use = { level = "allow" }
too_many_lines = { level = "allow" }
wildcard_imports = { level = "allow" }
# disable these for now, but we should probably fix them
default_trait_access = { level = "allow" }
explicit_into_iter_loop = { level = "allow" }
explicit_iter_loop = { level = "allow" }
from_iter_instead_of_collect = { level = "allow" }
ignored_unit_patterns = { level = "allow" }
implicit_clone = { level = "allow" }
manual_string_new = { level = "allow" }
match_same_arms = { level = "allow" }
match_wildcard_for_single_variants = { level = "allow" }
needless_pass_by_value = { level = "allow" }
redundant_closure_for_method_calls = { level = "allow" }
redundant_else = { level = "allow" }
semicolon_if_nothing_returned = { level = "allow" }
uninlined_format_args = { level = "allow" }
