[book]
authors = ["Phil Freeman"]
language = "en"
multilingual = false
src = "src"
title = "Hasura Data Connectors Developer's Guide"

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
