//! Property-based round-trip tests for the relational query model types.
//!
//! Rather than hand-writing one example test per enum variant (which is easy to
//! forget to extend when a new variant is added, and which only ever exercises a
//! single shape), we drive a single generic property over pseudo-randomly
//! generated values: every value must survive a JSON encode -> decode round trip
//! unchanged, and re-encoding the decoded value must be byte-identical (the wire
//! format is idempotent / normalized).
//!
//! Most generators come from `#[cfg_attr(test, derive(arbitrary::Arbitrary))]` on
//! the model types, so new variants and fields are covered automatically without
//! touching this file. The exceptions are hand-written below: the `Float32`/
//! `Float64` newtypes (bounded to JSON-round-trippable values) and
//! `RelationalLiteral` (which excludes a variant that cannot round-trip; see the
//! note on its impl). `arbitrary` is a dev-dependency only, and the derives are
//! gated on `cfg(test)`, so none of this affects the published crate.

#![allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]

use std::fmt::Debug;

use arbitrary::{Arbitrary, Unstructured};
use serde::{de::DeserializeOwned, Serialize};

use super::{Float32, Float64};

/// Number of independent pseudo-random seeds generated per type.
const SEEDS: usize = 256;
/// Size, in bytes, of each seed buffer. This bounds the depth/size of the
/// recursive structures we can build: `arbitrary` produces the simplest (leaf)
/// value once a buffer is exhausted, and its derived enum selection consumes
/// four bytes per level, so a 256-byte buffer caps nesting at ~64 levels. That
/// keeps the tests fast and free of runaway recursion, and stays comfortably
/// under `serde_json`'s default deserialization depth limit, while still
/// exercising deeply nested expressions.
const BUFFER_SIZE: usize = 256;
/// Upper bound on values pulled from a single seed buffer, as a backstop against
/// zero-consumption generators (e.g. unit structs) spinning forever.
const MAX_VALUES_PER_SEED: usize = 64;

// -- Generators for leaf types that need bounding ---------------------------

// Restrict generated floats to values that survive a JSON number round-trip, so
// the *model* round-trip property is well-defined. Two classes are excluded:
//   * non-finite floats (NaN/±Inf), which `serde_json` writes as `null` and then
//     cannot read back into a float (mirrors promptql-cloud's `arbitrary_finite_f32`);
//   * extreme-magnitude/subnormal floats, for which `serde_json`'s number
//     formatting and parsing are not exact inverses (a JSON-number limitation,
//     independent of these types — promptql-cloud avoids fuzzing floats for the
//     same reason).
// Anything excluded is coerced to `0.0`; the vast majority of values pass through.
fn json_round_trippable_f32(value: f32) -> f32 {
    if !value.is_finite() {
        return 0.0;
    }
    let survives = serde_json::to_string(&value)
        .ok()
        .and_then(|json| serde_json::from_str::<f32>(&json).ok())
        .is_some_and(|parsed| parsed.to_bits() == value.to_bits());
    if survives {
        value
    } else {
        0.0
    }
}

fn json_round_trippable_f64(value: f64) -> f64 {
    if !value.is_finite() {
        return 0.0;
    }
    let survives = serde_json::to_string(&value)
        .ok()
        .and_then(|json| serde_json::from_str::<f64>(&json).ok())
        .is_some_and(|parsed| parsed.to_bits() == value.to_bits());
    if survives {
        value
    } else {
        0.0
    }
}

impl<'a> Arbitrary<'a> for Float32 {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        Ok(Float32(json_round_trippable_f32(f32::arbitrary(u)?)))
    }
}

impl<'a> Arbitrary<'a> for Float64 {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        Ok(Float64(json_round_trippable_f64(f64::arbitrary(u)?)))
    }
}

// `RelationalLiteral` is generated by hand rather than derived so we can exclude
// the `Decimal128` variant. `Decimal128 { value: i128, .. }` does not round-trip
// through `serde_json`: `RelationalLiteral` (and every parent that nests it) is
// internally tagged (`#[serde(tag = "type")]`), so deserialization buffers into
// serde's `Content`, which returns "i128 is not supported"; and a full 128-bit
// value would in any case be truncated to `f64` during that buffering. This is a
// pre-existing limitation in the model, not something the test can assert away —
// see `decimal128_literal_is_a_known_non_round_trip`, which pins the current
// behavior, and the PR description for the suggested follow-up.
//
// IMPORTANT: any NEW `RelationalLiteral` variant must be added to this match.
impl<'a> Arbitrary<'a> for crate::RelationalLiteral {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        use crate::RelationalLiteral as Lit;
        Ok(match u.int_in_range(0u32..=28)? {
            0 => Lit::Null,
            1 => Lit::Boolean {
                value: bool::arbitrary(u)?,
            },
            2 => Lit::String {
                value: String::arbitrary(u)?,
            },
            3 => Lit::Int8 {
                value: i8::arbitrary(u)?,
            },
            4 => Lit::Int16 {
                value: i16::arbitrary(u)?,
            },
            5 => Lit::Int32 {
                value: i32::arbitrary(u)?,
            },
            6 => Lit::Int64 {
                value: i64::arbitrary(u)?,
            },
            7 => Lit::UInt8 {
                value: u8::arbitrary(u)?,
            },
            8 => Lit::UInt16 {
                value: u16::arbitrary(u)?,
            },
            9 => Lit::UInt32 {
                value: u32::arbitrary(u)?,
            },
            10 => Lit::UInt64 {
                value: u64::arbitrary(u)?,
            },
            11 => Lit::Float32 {
                value: Float32::arbitrary(u)?,
            },
            12 => Lit::Float64 {
                value: Float64::arbitrary(u)?,
            },
            // NB: Decimal128 (index intentionally skipped) — see note above.
            13 => Lit::Decimal256 {
                value: String::arbitrary(u)?,
                scale: i8::arbitrary(u)?,
                prec: u8::arbitrary(u)?,
            },
            14 => Lit::Date32 {
                value: i32::arbitrary(u)?,
            },
            15 => Lit::Date64 {
                value: i64::arbitrary(u)?,
            },
            16 => Lit::Time32Second {
                value: i32::arbitrary(u)?,
            },
            17 => Lit::Time32Millisecond {
                value: i32::arbitrary(u)?,
            },
            18 => Lit::Time64Microsecond {
                value: i64::arbitrary(u)?,
            },
            19 => Lit::Time64Nanosecond {
                value: i64::arbitrary(u)?,
            },
            20 => Lit::TimestampSecond {
                value: i64::arbitrary(u)?,
            },
            21 => Lit::TimestampMillisecond {
                value: i64::arbitrary(u)?,
            },
            22 => Lit::TimestampMicrosecond {
                value: i64::arbitrary(u)?,
            },
            23 => Lit::TimestampNanosecond {
                value: i64::arbitrary(u)?,
            },
            24 => Lit::DurationSecond {
                value: i64::arbitrary(u)?,
            },
            25 => Lit::DurationMillisecond {
                value: i64::arbitrary(u)?,
            },
            26 => Lit::DurationMicrosecond {
                value: i64::arbitrary(u)?,
            },
            27 => Lit::DurationNanosecond {
                value: i64::arbitrary(u)?,
            },
            _ => Lit::Interval {
                months: i32::arbitrary(u)?,
                days: i32::arbitrary(u)?,
                nanoseconds: i64::arbitrary(u)?,
            },
        })
    }
}

/// A small fixed pool of identifiers used to generate the string-newtype names
/// (`CollectionName`, `FieldName`, `ArgumentName`) that appear in `Relation`.
/// Fuzzing the full string space adds no meaningful coverage of the round-trip
/// property, but a handful of awkward names (empty, dotted, spaced, unicode)
/// guards the escaping paths.
const SAMPLE_NAMES: &[&str] = &["", "a", "col_1", "Namespace.Table", "with space", "🦀"];

macro_rules! arbitrary_name_newtype {
    ($ty:ty) => {
        impl<'a> Arbitrary<'a> for $ty {
            fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
                Ok(<$ty>::from(*u.choose(SAMPLE_NAMES)?))
            }
        }
    };
}

arbitrary_name_newtype!(crate::CollectionName);
arbitrary_name_newtype!(crate::FieldName);
arbitrary_name_newtype!(crate::ArgumentName);

// -- The round-trip driver --------------------------------------------------

/// Assert the JSON round-trip property for `T` over many generated values:
///
/// * encode -> decode -> semantic equality (`value == decode(encode(value))`),
///   which catches any field or variant that is dropped or mangled on the wire;
/// * decode -> encode normalization (`encode(value) == encode(decode(...))`),
///   which catches a `PartialEq` that is coarser than the serialization and any
///   non-deterministic/duplicated serialization.
fn assert_round_trips<T>()
where
    T: for<'a> Arbitrary<'a> + Serialize + DeserializeOwned + PartialEq + Debug,
{
    let type_name = std::any::type_name::<T>();
    let mut generated = 0usize;

    for seed_index in 0..SEEDS {
        let buffer = high_entropy_seed(type_name, seed_index);
        let mut unstructured = Unstructured::new(&buffer);

        for _ in 0..MAX_VALUES_PER_SEED {
            let remaining_before = unstructured.len();
            // buffer exhausted for this seed
            let Ok(value) = T::arbitrary(&mut unstructured) else {
                break;
            };
            generated += 1;

            let encoded = serde_json::to_string(&value)
                .unwrap_or_else(|err| panic!("failed to serialize {type_name}: {err}"));
            let decoded: T = serde_json::from_str(&encoded).unwrap_or_else(|err| {
                panic!("failed to deserialize {type_name} from `{encoded}`: {err}")
            });
            assert_eq!(
                value, decoded,
                "encode -> decode changed a {type_name} value; json = {encoded}"
            );

            let reencoded = serde_json::to_string(&decoded)
                .unwrap_or_else(|err| panic!("failed to re-serialize {type_name}: {err}"));
            assert_eq!(
                encoded, reencoded,
                "decode -> encode was not idempotent for {type_name}"
            );

            // Stop if the generator made no progress (a zero-sized type), to
            // avoid spinning on a buffer that will never drain.
            if unstructured.len() == remaining_before {
                break;
            }
        }
    }

    assert!(
        generated > 0,
        "generated no arbitrary values for {type_name}; increase BUFFER_SIZE"
    );
}

/// A deterministic, dependency-free pseudo-random seed buffer derived from the
/// type name and seed index (a PCG-style LCG). Determinism keeps the tests
/// reproducible in CI; keying on the type name gives each type a distinct stream.
fn high_entropy_seed(type_name: &str, seed_index: usize) -> Vec<u8> {
    let mut state = type_name
        .bytes()
        .fold(0xcbf2_9ce4_8422_2325_u64, |acc, byte| {
            (acc ^ u64::from(byte)).wrapping_mul(0x0000_0100_0000_01b3)
        });
    state = state
        .wrapping_add((seed_index as u64).wrapping_mul(0x9e37_79b9_7f4a_7c15))
        .wrapping_add(1);

    let mut buffer = Vec::with_capacity(BUFFER_SIZE);
    for _ in 0..BUFFER_SIZE {
        state = state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        buffer.push((state >> 33) as u8);
    }
    buffer
}

/// Run a property test on a thread with a generous stack. Deeply nested
/// expressions can otherwise overflow the default (smaller) test-thread stack
/// during (de)serialization or drop; this keeps the tests robust regardless of
/// the depth `arbitrary` happens to produce.
fn with_large_stack(test: impl FnOnce() + Send + 'static) {
    std::thread::Builder::new()
        .stack_size(64 * 1024 * 1024)
        .spawn(test)
        .expect("failed to spawn property-test thread")
        .join()
        .expect("property-test thread panicked");
}

// -- Tests ------------------------------------------------------------------

// `RelationalExpression` is the type the review comment
// (https://github.com/hasura/ndc-spec/pull/259#discussion_r4127661528) is about:
// this single property replaces per-variant example tests and covers every
// current and future variant reachable from it (literals, casts, sorts,
// case/when, window functions, ...).
#[test]
fn relational_expression_round_trips() {
    with_large_stack(assert_round_trips::<super::RelationalExpression>);
}

#[test]
fn relational_literal_round_trips() {
    with_large_stack(assert_round_trips::<super::RelationalLiteral>);
}

#[test]
fn cast_type_round_trips() {
    with_large_stack(assert_round_trips::<super::CastType>);
}

#[test]
fn sort_round_trips() {
    with_large_stack(assert_round_trips::<super::Sort>);
}

#[test]
fn case_when_round_trips() {
    with_large_stack(assert_round_trips::<super::CaseWhen>);
}

#[test]
fn date_part_unit_round_trips() {
    with_large_stack(assert_round_trips::<super::DatePartUnit>);
}

#[test]
fn relation_round_trips() {
    with_large_stack(assert_round_trips::<super::Relation>);
}

#[test]
fn join_on_round_trips() {
    with_large_stack(assert_round_trips::<super::JoinOn>);
}

// Also cover the capabilities tree touched by the same feature area (the
// window-expression capabilities in particular), in one shot from the root.
#[test]
fn relational_query_capabilities_round_trips() {
    with_large_stack(assert_round_trips::<crate::RelationalQueryCapabilities>);
}

// Pins a pre-existing limitation the property test surfaced: a `Decimal128`
// literal cannot be deserialized from its own serialized form, because
// `RelationalLiteral` is internally tagged and serde's `Content` buffer does not
// support `i128` ("i128 is not supported"). The fuzz generator for
// `RelationalLiteral` excludes `Decimal128` for this reason. If this test starts
// to fail (e.g. the model switches `value` to a string like `Decimal256`, or
// serde/serde_json gain the support), remove the exclusion from that generator
// and delete this pin. See the PR description for the suggested follow-up fix.
#[test]
fn decimal128_literal_is_a_known_non_round_trip() {
    let literal = crate::RelationalLiteral::Decimal128 {
        value: 1,
        scale: 0,
        prec: 1,
    };
    let json = serde_json::to_string(&literal).expect("Decimal128 should still serialize");
    let decoded = serde_json::from_str::<crate::RelationalLiteral>(&json);
    assert!(
        decoded.is_err(),
        "Decimal128 unexpectedly round-tripped ({json}); it is now safe to include \
         it in the RelationalLiteral fuzz generator in proptests.rs and delete this pin"
    );
}
