name: Build and test
on: push

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: install rust toolchain
        run: |
          rustup show

      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          shared-key: "build"

      - name: cargo check --all-targets
        run: |
          cargo check --all-targets

      # Sadly, `cargo build --locked` isn't enough to check that the lockfile
      # is up to date, as it will happily run even if there are extra entries in
      # there.
      #
      # It does, however, make sure that the file is not updated, which is quite
      # unhelpful.
      - name: ensure lockfile hasn't changed
        run: |
          if [[ -n "$(git status --porcelain Cargo.lock)" ]]; then
            echo 'The Cargo.lock file was changed!'
            git diff Cargo.lock
            exit 1
          fi

  lint:
    name: just lint
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install rust toolchain
        run: |
          rustup show

      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          shared-key: "build"

      - name: just lint
        run: |
          just lint

  test:
    name: just test
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install cargo nextest
        uses: taiki-e/install-action@aed063e1f30df6b3706dd77fc425d37778911ac2 # nextest

      - name: install rust toolchain
        run: |
          rustup show

      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          shared-key: "test"

      - name: just test
        run: |
          just test

  build-docs:
    name: just build-docs
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install mdbook
        uses: taiki-e/install-action@3b1a85d4f6672e7485a86e2dc81017a4bf42fc56 # mdbook

      - name: install rust toolchain
        run: |
          rustup show

      - name: install mdbook-pagetoc
        run: |
          cargo install mdbook-pagetoc

      - name: just build-docs
        run: |
          just build-docs
